### ISSUE TITLE
Devolutiva primeiro desafio - Lógica com JS

### ISSUE THREAD

**Issue by MateusPaixao** [AfranioCaires/Exercicios-Ada#1]
![image](https://github.com/AfranioCaires/Exercicios-Ada/assets/20425031/9dd1fad6-3efe-4a6c-9ee4-518c29a5e7b9)

- Bom uso de `let` e `const`
- Bom uso de **Objetos**
- Bom uso do `for-in`
- Bom uso de operadores **aritméticos** e de **atribuição**
- Conseguiu chegar no resultado final esperado

Dicas/Sugestão: Agora que entendeu o uso de objetos, e já sabe utilizar o for-in que tal utilizar arrays e função nativa como forEach?

No mais, excelente entrega parabéns. 💚🚀

**Comment by AfranioCaires** [comment]
Obrigado pelo review, professor
